In [2]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")
pd.set_option("display.max_columns",None)

In [3]:
sub_df= pd.read_csv("bank-additional-full.csv",header=0,delimiter=';',index_col=None)

In [4]:
sub_df.head(10)

age          job  marital            education  default housing loan  \
0   56    housemaid  married             basic.4y       no      no   no   
1   57     services  married          high.school  unknown      no   no   
2   37     services  married          high.school       no     yes   no   
3   40       admin.  married             basic.6y       no      no   no   
4   56     services  married          high.school       no      no  yes   
5   45     services  married             basic.9y  unknown      no   no   
6   59       admin.  married  professional.course       no      no   no   
7   41  blue-collar  married              unknown  unknown      no   no   
8   24   technician   single  professional.course       no     yes   no   
9   25     services   single          high.school       no     yes   no   

     contact month day_of_week  duration  campaign  pdays  previous  \
0  telephone   may         mon       261         1    999         0   
1  telephone   may         mon       149         1    999         0   
2  telephone   may         mon       226         1    999         0   
3  telephone   may         mon       151         1    999         0   
4  telephone   may         mon       307         1    999         0   
5  telephone   may         mon       198         1    999         0   
6  telephone   may         mon       139         1    999         0   
7  telephone   may         mon       217         1    999         0   
8  telephone   may         mon       380         1    999         0   
9  telephone   may         mon        50         1    999         0   

      poutcome  emp.var.rate  cons.price.idx  cons.conf.idx  euribor3m  \
0  nonexistent           1.1          93.994          -36.4      4.857   
1  nonexistent           1.1          93.994          -36.4      4.857   
2  nonexistent           1.1          93.994          -36.4      4.857   
3  nonexistent           1.1          93.994          -36.4      4.857   
4  nonexistent           1.1          93.994          -36.4      4.857   
5  nonexistent           1.1          93.994          -36.4      4.857   
6  nonexistent           1.1          93.994          -36.4      4.857   
7  nonexistent           1.1          93.994          -36.4      4.857   
8  nonexistent           1.1          93.994          -36.4      4.857   
9  nonexistent           1.1          93.994          -36.4      4.857   

   nr.employed   y  
0       5191.0  no  
1       5191.0  no  
2       5191.0  no  
3       5191.0  no  
4       5191.0  no  
5       5191.0  no  
6       5191.0  no  
7       5191.0  no  
8       5191.0  no  
9       5191.0  no

In [5]:
sub_df.isnull().sum()

age               0
job               0
marital           0
education         0
default           0
housing           0
loan              0
contact           0
month             0
day_of_week       0
duration          0
campaign          0
pdays             0
previous          0
poutcome          0
emp.var.rate      0
cons.price.idx    0
cons.conf.idx     0
euribor3m         0
nr.employed       0
y                 0
dtype: int64

In [6]:
sub_df.shape

(41188, 21)

In [7]:
sub_df.dtypes

age                 int64
job                object
marital            object
education          object
default            object
housing            object
loan               object
contact            object
month              object
day_of_week        object
duration            int64
campaign            int64
pdays               int64
previous            int64
poutcome           object
emp.var.rate      float64
cons.price.idx    float64
cons.conf.idx     float64
euribor3m         float64
nr.employed       float64
y                  object
dtype: object

In [8]:
colname=sub_df.columns
colname

Index(['age', 'job', 'marital', 'education', 'default', 'housing', 'loan',
       'contact', 'month', 'day_of_week', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'emp.var.rate', 'cons.price.idx',
       'cons.conf.idx', 'euribor3m', 'nr.employed', 'y'],
      dtype='object')

In [9]:
##Coverting object data to numeric
from sklearn import preprocessing
le=preprocessing.LabelEncoder()
for x in colname:
    sub_df[x]=le.fit_transform(sub_df[x])

In [10]:
sub_df.head(10)

age  job  marital  education  default  housing  loan  contact  month  \
0   39    3        1          0        0        0     0        1      6   
1   40    7        1          3        1        0     0        1      6   
2   20    7        1          3        0        2     0        1      6   
3   23    0        1          1        0        0     0        1      6   
4   39    7        1          3        0        0     2        1      6   
5   28    7        1          2        1        0     0        1      6   
6   42    0        1          5        0        0     0        1      6   
7   24    1        1          7        1        0     0        1      6   
8    7    9        2          5        0        2     0        1      6   
9    8    7        2          3        0        2     0        1      6   

   day_of_week  duration  campaign  pdays  previous  poutcome  emp.var.rate  \
0            1       261         0     26         0         1             8   
1            1       149         0     26         0         1             8   
2            1       226         0     26         0         1             8   
3            1       151         0     26         0         1             8   
4            1       307         0     26         0         1             8   
5            1       198         0     26         0         1             8   
6            1       139         0     26         0         1             8   
7            1       217         0     26         0         1             8   
8            1       380         0     26         0         1             8   
9            1        50         0     26         0         1             8   

   cons.price.idx  cons.conf.idx  euribor3m  nr.employed  y  
0              18             16        287            8  0  
1              18             16        287            8  0  
2              18             16        287            8  0  
3              18             16        287            8  0  
4              18             16        287            8  0  
5              18             16        287            8  0  
6              18             16        287            8  0  
7              18             16        287            8  0  
8              18             16        287            8  0  
9              18             16        287            8  0

In [11]:
sub_df.dtypes

age               int64
job               int32
marital           int32
education         int32
default           int32
housing           int32
loan              int32
contact           int32
month             int32
day_of_week       int32
duration          int64
campaign          int64
pdays             int64
previous          int64
poutcome          int32
emp.var.rate      int64
cons.price.idx    int64
cons.conf.idx     int64
euribor3m         int64
nr.employed       int64
y                 int32
dtype: object

In [12]:
sub_df["y"].value_counts()

0    36548
1     4640
Name: y, dtype: int64

In [13]:
##We do upsampling here because the data is imbalanced 
##Therefore we umsample data in 1:1 ratio
from sklearn.utils import resample
# Separate majority and minority classes
df_majority = sub_df[sub_df.y==0] ##NO class
df_minority = sub_df[sub_df.y==1] ##YES class

# Upsample minority class
df_minority_upsampled = resample(df_minority, 
replace=True, # sample with replacement
n_samples=36548, # to match majority class
random_state=10) # reproducible results

# Combine majority class with upsampled minority class
df_upsampled = pd.concat([df_majority, df_minority_upsampled])

# Display new class counts
df_upsampled.y.value_counts()

1    36548
0    36548
Name: y, dtype: int64

In [14]:
X=df_upsampled.values[:,:-1] #All rows , columns starting from 0
Y=df_upsampled.values[:,-1] #All rows , only column -1, dependent variable
Y=Y.astype(int)

In [15]:
##Converts each var such thea the mean=0 and SD=1 , range(-3 to +3)(usual-->Not affected by outliers)
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
#scaler.fit(X)
X=scaler.fit_transform(X)

print(X)

[[ 1.29528304 -0.22758352 -0.3389797  ...  0.77423663  0.70294255
   0.40141493]
 [ 1.37833357  0.87897481 -0.3389797  ...  0.77423663  0.70294255
   0.40141493]
 [-0.28267697  0.87897481 -0.3389797  ...  0.77423663  0.70294255
   0.40141493]
 ...
 [-1.03013172 -1.05750226  1.27701586 ...  0.17366729 -2.25145459
  -1.55773257]
 [ 0.63087883 -0.78086268 -0.3389797  ...  0.77423663  0.74804785
   0.40141493]
 [-1.2792833  -1.05750226  1.27701586 ... -0.72718672  0.92846905
   1.05446409]]


In [16]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3,random_state=10)

In [17]:
from sklearn.linear_model import LogisticRegression
classifier=LogisticRegression()
classifier.fit(X_train,Y_train)
Y_pred=classifier.predict(X_test)
print()
print(classifier.coef_)
print()
print(classifier.intercept_)


[[ 0.1361081   0.05966532  0.11135721  0.17003372 -0.2030684   0.00240585
  -0.04093245 -0.21775584 -0.27787467  0.05427968  2.17625258 -0.08796333
  -0.31489771 -0.0353685   0.25163664 -0.74583522  0.14625245  0.10892644
  -0.1527506  -0.75460395]]

[0.12879072]


In [18]:
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report
print(confusion_matrix(Y_test,Y_pred))
print()
print(accuracy_score(Y_test,Y_pred))
print()
print(classification_report(Y_test,Y_pred))

[[9308 1643]
 [1493 9485]]

0.8569930229376624

              precision    recall  f1-score   support

           0       0.86      0.85      0.86     10951
           1       0.85      0.86      0.86     10978

    accuracy                           0.86     21929
   macro avg       0.86      0.86      0.86     21929
weighted avg       0.86      0.86      0.86     21929




# SVM

In [18]:
from sklearn import svm
classifier=svm.SVC(kernel="rbf", C=1.0, gamma=0.1) 
classifier.fit(X_train,Y_train)     
Y_pred=classifier.predict(X_test)   
print(list(zip(Y_test,Y_pred)))

[(1, 1), (0, 0), (0, 0), (1, 1), (0, 1), (0, 0), (0, 0), (0, 1), (1, 1), (1, 1), (0, 0), (0, 0), (0, 0), (0, 0), (1, 1), (0, 0), (1, 1), (1, 1), (1, 1), (1, 1), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 1), (1, 1), (0, 1), (1, 1), (1, 1), (1, 1), (0, 0), (1, 1), (0, 0), (0, 0), (1, 1), (1, 1), (1, 1), (1, 0), (0, 1), (0, 0), (1, 1), (1, 1), (0, 0), (1, 1), (1, 1), (1, 1), (1, 1), (1, 1), (0, 0), (0, 0), (0, 1), (1, 1), (0, 0), (1, 1), (0, 1), (0, 0), (1, 1), (1, 1), (1, 1), (0, 0), (1, 1), (0, 0), (0, 0), (0, 0), (1, 1), (0, 1), (1, 1), (0, 1), (0, 0), (0, 1), (1, 1), (1, 1), (1, 1), (1, 1), (1, 1), (0, 1), (0, 0), (0, 0), (0, 0), (1, 1), (1, 1), (1, 1), (0, 0), (0, 0), (1, 1), (1, 1), (0, 1), (0, 0), (1, 1), (1, 1), (1, 1), (1, 1), (0, 0), (0, 0), (0, 0), (1, 1), (0, 0), (0, 0), (0, 0), (0, 0), (1, 1), (1, 1), (0, 0), (0, 0), (1, 1), (1, 1), (1, 1), (0, 0), (1, 1), (1, 1), (1, 1), (1, 1), (0, 0), (1, 1), (1, 1), (1, 1), (0, 0), (1, 1), (0, 0), (0, 0), (1, 1), (0, 0), (0, 0),

In [19]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
print(confusion_matrix(Y_test,Y_pred))
print()
print(accuracy_score(Y_test,Y_pred))
print()
print(classification_report(Y_test,Y_pred))

[[ 9378  1573]
 [  422 10556]]

0.9090245793241826

              precision    recall  f1-score   support

           0       0.96      0.86      0.90     10951
           1       0.87      0.96      0.91     10978

    accuracy                           0.91     21929
   macro avg       0.91      0.91      0.91     21929
weighted avg       0.91      0.91      0.91     21929



In [19]:
##Model building using DT
from sklearn.tree import DecisionTreeClassifier

##Creating model object
model_DT=DecisionTreeClassifier(criterion="gini",random_state=10)

##Train the model
model_DT.fit(X_train,Y_train)


DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=10, splitter='best')

In [33]:
##Pruning done here 
from sklearn.tree import DecisionTreeClassifier

##Creating model object
model_DT=DecisionTreeClassifier(criterion="gini",min_samples_leaf=5, max_depth=10, random_state=10)

##Train the model
model_DT.fit(X_train,Y_train)



DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=10,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=5, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=10, splitter='best')

In [24]:
##DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
##            max_features=None-->(specifies the num of variables), max_leaf_nodes=None-->(specifies the dept of tree),
##            min_impurity_decrease=0.0, min_impurity_split=None,
##            min_samples_leaf=1, min_samples_split=2,
##            min_weight_fraction_leaf=0.0, presort=False, random_state=10,
##            splitter='best')

In [20]:
##Prediction
Y_pred=model_DT.predict(X_test)
Y_pred

array([1, 0, 0, ..., 0, 0, 0])

In [21]:
##Zipping og values with predicted values
print(list(zip(Y_test,Y_pred)))

[(1, 1), (0, 0), (0, 0), (1, 1), (0, 0), (0, 1), (0, 0), (0, 0), (1, 1), (1, 1), (0, 0), (0, 0), (0, 0), (0, 0), (1, 1), (0, 0), (1, 1), (1, 1), (1, 1), (1, 1), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (1, 1), (0, 0), (1, 1), (1, 1), (1, 1), (0, 0), (1, 1), (0, 0), (0, 0), (1, 1), (1, 1), (1, 1), (1, 1), (0, 0), (0, 0), (1, 1), (1, 1), (0, 0), (1, 1), (1, 1), (1, 1), (1, 1), (1, 1), (0, 0), (0, 0), (0, 1), (1, 1), (0, 0), (1, 1), (0, 0), (0, 0), (1, 1), (1, 1), (1, 1), (0, 0), (1, 1), (0, 0), (0, 0), (0, 0), (1, 1), (0, 1), (1, 1), (0, 0), (0, 0), (0, 0), (1, 1), (1, 1), (1, 1), (1, 1), (1, 1), (0, 1), (0, 0), (0, 0), (0, 0), (1, 1), (1, 1), (1, 1), (0, 0), (0, 0), (1, 1), (1, 1), (0, 0), (0, 0), (1, 1), (1, 1), (1, 1), (1, 1), (0, 0), (0, 0), (0, 0), (1, 1), (0, 0), (0, 0), (0, 0), (0, 0), (1, 1), (1, 1), (0, 0), (0, 0), (1, 1), (1, 1), (1, 1), (0, 0), (1, 1), (1, 1), (1, 1), (1, 1), (0, 0), (1, 1), (1, 1), (1, 1), (0, 0), (1, 1), (0, 0), (0, 0), (1, 1), (0, 0), (0, 0),

In [22]:
###Model Evaluation
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

print(confusion_matrix(Y_test,Y_pred))

print(accuracy_score(Y_test,Y_pred))

print(classification_report(Y_test,Y_pred))



[[10169   782]
 [   17 10961]]
0.9635642300150485
              precision    recall  f1-score   support

           0       1.00      0.93      0.96     10951
           1       0.93      1.00      0.96     10978

    accuracy                           0.96     21929
   macro avg       0.97      0.96      0.96     21929
weighted avg       0.97      0.96      0.96     21929



# TUNNED SVM

In [28]:
##Tuning the SVM for Classification, Cost=50
##Accuracy obtained= 99.61%
from sklearn import svm
classifier=svm.SVC(kernel="rbf", C=50, gamma=0.1) ##Creating model object and defining kernel,gamma,cost
classifier.fit(X_train,Y_train)     ##Training the model for givenX-train on Y-train
Y_pred=classifier.predict(X_test)   ##Testing the model and predicting values on the X_test
print(list(zip(Y_test,Y_pred)))

[(1, 1), (0, 0), (0, 0), (1, 1), (0, 1), (0, 0), (0, 0), (0, 0), (1, 1), (1, 1), (0, 0), (0, 0), (0, 0), (0, 0), (1, 1), (0, 0), (1, 1), (1, 1), (1, 1), (1, 1), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (1, 1), (0, 0), (1, 1), (1, 1), (1, 1), (0, 0), (1, 0), (0, 0), (0, 0), (1, 1), (1, 1), (1, 1), (1, 1), (0, 1), (0, 0), (1, 1), (1, 1), (0, 0), (1, 1), (1, 1), (1, 1), (1, 1), (1, 1), (0, 0), (0, 0), (0, 1), (1, 1), (0, 0), (1, 1), (0, 0), (0, 0), (1, 1), (1, 1), (1, 1), (0, 0), (1, 1), (0, 0), (0, 0), (0, 0), (1, 1), (0, 0), (1, 1), (0, 0), (0, 0), (0, 0), (1, 1), (1, 1), (1, 1), (1, 1), (1, 1), (0, 0), (0, 0), (0, 0), (0, 0), (1, 1), (1, 1), (1, 1), (0, 0), (0, 0), (1, 1), (1, 1), (0, 0), (0, 0), (1, 1), (1, 1), (1, 1), (1, 1), (0, 0), (0, 0), (0, 0), (1, 1), (0, 0), (0, 0), (0, 0), (0, 0), (1, 1), (1, 1), (0, 0), (0, 0), (1, 1), (1, 1), (1, 1), (0, 0), (1, 1), (1, 1), (1, 1), (1, 1), (0, 0), (1, 1), (1, 1), (1, 1), (0, 0), (1, 1), (0, 0), (0, 0), (1, 1), (0, 0), (0, 0),

In [40]:
###Model Evaluation for SVM
##Accuracy obtained= 99.61%
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

print(confusion_matrix(Y_test,Y_pred))

print(accuracy_score(Y_test,Y_pred))

print(classification_report(Y_test,Y_pred))


[[9308 1643]
 [1493 9485]]
0.8569930229376624
              precision    recall  f1-score   support

           0       0.86      0.85      0.86     10951
           1       0.85      0.86      0.86     10978

    accuracy                           0.86     21929
   macro avg       0.86      0.86      0.86     21929
weighted avg       0.86      0.86      0.86     21929



In [54]:
#predicting using the Bagging_Classifier ExtraTreesClassifier
from sklearn.ensemble import ExtraTreesClassifier
 
model=ExtraTreesClassifier(100,random_state=10)
#fit the model on the data and predict the values
model=model.fit(X_train,Y_train)
 
Y_pred=model.predict(X_test)

In [55]:
###Model Evaluation for ExtraTreesClassifier
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

print(confusion_matrix(Y_test,Y_pred))

print(accuracy_score(Y_test,Y_pred))

print(classification_report(Y_test,Y_pred))


[[10487   464]
 [   19 10959]]
0.977974371836381
              precision    recall  f1-score   support

           0       1.00      0.96      0.98     10951
           1       0.96      1.00      0.98     10978

    accuracy                           0.98     21929
   macro avg       0.98      0.98      0.98     21929
weighted avg       0.98      0.98      0.98     21929



In [43]:
#predicting using the Random_Forest_Classifier
##Accuracy obtained= 98.26
from sklearn.ensemble import RandomForestClassifier
 
model_RandomForest=RandomForestClassifier(n_estimators=10,random_state=10)
 
#fit the model on the data and predict the values
model_RandomForest.fit(X_train,Y_train)
 
Y_pred=model_RandomForest.predict(X_test)

In [44]:
###Model Evaluation for RANDOM FOREST
##Accuracy obtained= 98.26
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

print(confusion_matrix(Y_test,Y_pred))

print(accuracy_score(Y_test,Y_pred))

print(classification_report(Y_test,Y_pred))


[[10261   690]
 [   14 10964]]
0.9678963929043732
              precision    recall  f1-score   support

           0       1.00      0.94      0.97     10951
           1       0.94      1.00      0.97     10978

    accuracy                           0.97     21929
   macro avg       0.97      0.97      0.97     21929
weighted avg       0.97      0.97      0.97     21929



In [45]:
#predicting using the AdaBoost_Classifier
from sklearn.ensemble import AdaBoostClassifier
 
model_AdaBoost=AdaBoostClassifier(base_estimator=DecisionTreeClassifier(),
                                  n_estimators=101, #default n_estimators=50
                                  random_state=10)
#fit the model on the data and predict the values
model_AdaBoost.fit(X_train,Y_train)
Y_pred=model_AdaBoost.predict(X_test)
 

 


In [46]:
###Model Evaluation for AdaBoostClassifier
##Accuracy obtained= 98.45
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

print(confusion_matrix(Y_test,Y_pred))

print(accuracy_score(Y_test,Y_pred))

print(classification_report(Y_test,Y_pred))

[[10181   770]
 [   17 10961]]
0.9641114505905422
              precision    recall  f1-score   support

           0       1.00      0.93      0.96     10951
           1       0.93      1.00      0.97     10978

    accuracy                           0.96     21929
   macro avg       0.97      0.96      0.96     21929
weighted avg       0.97      0.96      0.96     21929



In [47]:
#predicting using the Gradient_Boosting_Classifier
from sklearn.ensemble import GradientBoostingClassifier
 
model_GradientBoosting=GradientBoostingClassifier(n_estimators=100, #default n_estimators=100
                                                  random_state=10)
 
#fit the model on the data and predict the values
model_GradientBoosting.fit(X_train,Y_train)
 
Y_pred=model_GradientBoosting.predict(X_test)

In [48]:
###Model Evaluation for Gradient_Boosting_Classifier
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

print(confusion_matrix(Y_test,Y_pred))

print(accuracy_score(Y_test,Y_pred))

print(classification_report(Y_test,Y_pred))

[[ 9275  1676]
 [  692 10286]]
0.8920151397692553
              precision    recall  f1-score   support

           0       0.93      0.85      0.89     10951
           1       0.86      0.94      0.90     10978

    accuracy                           0.89     21929
   macro avg       0.90      0.89      0.89     21929
weighted avg       0.90      0.89      0.89     21929



In [49]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import VotingClassifier ##Creatin this ensembled model
from sklearn.neighbors import KNeighborsClassifier
 
# create the sub models
estimators = []
#model1 = LogisticRegression()
#estimators.append(('log', model1)) ##log for logistic , it can be any name
model2 = DecisionTreeClassifier(criterion='gini',random_state=10)
estimators.append(('cart', model2))
model3 = SVC(kernel="rbf", C=50,gamma=0.1)
estimators.append(('svm', model3))
#model4 = KNeighborsClassifier(n_neighbors=5, metric='euclidean')
#estimators.append(('knn', model4))
 
    
# create the ensemble model
ensemble = VotingClassifier(estimators)
ensemble.fit(X_train,Y_train)
Y_pred=ensemble.predict(X_test)
#print(Y_pred)

In [39]:

from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

print(confusion_matrix(Y_test,Y_pred))

print(accuracy_score(Y_test,Y_pred))

print(classification_report(Y_test,Y_pred))

[[10670   265]
 [  986   436]]
0.898761835396941
              precision    recall  f1-score   support

           0       0.92      0.98      0.94     10935
           1       0.62      0.31      0.41      1422

    accuracy                           0.90     12357
   macro avg       0.77      0.64      0.68     12357
weighted avg       0.88      0.90      0.88     12357



In [50]:
###Model building
## predicting using the KNeighbors_Classifier
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
model_KNN=KNeighborsClassifier(n_neighbors=int(round(np.sqrt(len(X_train)),0)),metric="euclidean")

model_KNN.fit(X_train,Y_train)

Y_pred=model_KNN.predict(X_test)
print(list(zip(Y_test,Y_pred)))


[(1, 1), (0, 0), (0, 0), (1, 1), (0, 1), (0, 0), (0, 0), (0, 1), (1, 1), (1, 1), (0, 0), (0, 0), (0, 0), (0, 0), (1, 1), (0, 0), (1, 1), (1, 0), (1, 1), (1, 1), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (1, 1), (0, 1), (1, 0), (1, 1), (1, 1), (0, 0), (1, 0), (0, 0), (0, 0), (1, 1), (1, 1), (1, 0), (1, 0), (0, 1), (0, 0), (1, 1), (1, 1), (0, 0), (1, 0), (1, 1), (1, 1), (1, 1), (1, 0), (0, 0), (0, 0), (0, 1), (1, 1), (0, 0), (1, 1), (0, 0), (0, 0), (1, 1), (1, 1), (1, 1), (0, 0), (1, 1), (0, 0), (0, 0), (0, 0), (1, 1), (0, 0), (1, 1), (0, 1), (0, 0), (0, 0), (1, 0), (1, 1), (1, 1), (1, 1), (1, 0), (0, 1), (0, 0), (0, 0), (0, 0), (1, 1), (1, 0), (1, 0), (0, 0), (0, 0), (1, 1), (1, 1), (0, 0), (0, 0), (1, 1), (1, 1), (1, 1), (1, 1), (0, 0), (0, 0), (0, 0), (1, 1), (0, 1), (0, 0), (0, 0), (0, 0), (1, 1), (1, 1), (0, 1), (0, 0), (1, 1), (1, 0), (1, 1), (0, 0), (1, 1), (1, 0), (1, 1), (1, 1), (0, 0), (1, 1), (1, 1), (1, 1), (0, 0), (1, 1), (0, 1), (0, 0), (1, 1), (0, 0), (0, 0),

In [51]:
int(round(np.sqrt(len(X_train)),0))

226

In [52]:
###Model Evaluation
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report

cfm= confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report:")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test,Y_pred)
print("Accuracy of the model:", acc)

[[9362 1589]
 [1948 9030]]
Classification report:
              precision    recall  f1-score   support

           0       0.83      0.85      0.84     10951
           1       0.85      0.82      0.84     10978

    accuracy                           0.84     21929
   macro avg       0.84      0.84      0.84     21929
weighted avg       0.84      0.84      0.84     21929

Accuracy of the model: 0.83870673537325


In [53]:
#Testing range of K VALUES 
from sklearn.metrics import accuracy_score
for K in range(1,31): ##Range of K
    model_KNN = KNeighborsClassifier(K,metric="euclidean")
    model_KNN.fit(X_train, Y_train) 
    Y_pred = model_KNN.predict(X_test)
    print ("Accuracy is ", accuracy_score(Y_test,Y_pred), "for K-Value:",K)


Accuracy is  0.9614665511423229 for K-Value: 1
Accuracy is  0.9559943453873866 for K-Value: 2
Accuracy is  0.9354735738063751 for K-Value: 3
Accuracy is  0.9287245200419536 for K-Value: 4
Accuracy is  0.9161840485202244 for K-Value: 5
Accuracy is  0.9061972730174654 for K-Value: 6
Accuracy is  0.8997674312554153 for K-Value: 7
Accuracy is  0.893337589493365 for K-Value: 8
Accuracy is  0.8875461717360573 for K-Value: 9
Accuracy is  0.8837612294222262 for K-Value: 10
Accuracy is  0.8809339231155091 for K-Value: 11
Accuracy is  0.8777418030917963 for K-Value: 12
Accuracy is  0.8772857859455515 for K-Value: 13
Accuracy is  0.8731816316293493 for K-Value: 14
Accuracy is  0.8722695973368598 for K-Value: 15
Accuracy is  0.8713575630443705 for K-Value: 16
Accuracy is  0.8700807150348853 for K-Value: 17
Accuracy is  0.8677550275890373 for K-Value: 18
Accuracy is  0.8683478498791555 for K-Value: 19
Accuracy is  0.8673446121574171 for K-Value: 20
Accuracy is  0.8688950704546491 for K-Value: 21
Ac

In [39]:
###REbuilding Model using new K value , K=26 gives highest accuracy above therefore we take K=26
## predicting using the KNeighbors_Classifier
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
model_KNN=KNeighborsClassifier(n_neighbors=26 ,metric="euclidean")

model_KNN.fit(X_train,Y_train)

Y_pred=model_KNN.predict(X_test)
print(list(zip(Y_test,Y_pred)))


[(2.0, 2.0), (2.0, 2.0), (1.0, 1.0), (2.0, 2.0), (1.0, 1.0), (2.0, 2.0), (2.0, 2.0), (1.0, 1.0), (3.0, 3.0), (1.0, 1.0), (1.0, 1.0), (2.0, 2.0), (1.0, 1.0), (2.0, 2.0), (2.0, 2.0), (2.0, 2.0), (2.0, 3.0), (2.0, 2.0), (2.0, 2.0), (3.0, 3.0), (1.0, 1.0), (3.0, 3.0), (1.0, 1.0), (1.0, 1.0), (2.0, 2.0), (3.0, 3.0), (2.0, 2.0), (3.0, 3.0), (2.0, 2.0), (2.0, 2.0), (3.0, 3.0), (3.0, 3.0), (2.0, 2.0), (3.0, 3.0), (2.0, 2.0), (1.0, 1.0)]


In [40]:
## Evaluating the New Model
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report

cfm= confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report:")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test,Y_pred)
print("Accuracy of the model:", acc)

##Only 1 misclassified usin K=26

[[10  0  0]
 [ 0 17  1]
 [ 0  0  8]]
Classification report:
              precision    recall  f1-score   support

         1.0       1.00      1.00      1.00        10
         2.0       1.00      0.94      0.97        18
         3.0       0.89      1.00      0.94         8

   micro avg       0.97      0.97      0.97        36
   macro avg       0.96      0.98      0.97        36
weighted avg       0.98      0.97      0.97        36

Accuracy of the model: 0.9722222222222222
